fixtures:

  forge_modules:

    puppi: "example42/puppi"
    stdlib: 'puppetlabs/stdlib'

    epel: 'stahnma/epel'
    java: 'puppetlabs/java'

    concat: 'puppetlabs/concat' # Dependency for PostgreSQL
    postgresql: 'puppetlabs/postgresql'

    firewall: 'puppetlabs/firewall'

    rvm: 'maestrodev/rvm'

  repositories:

    fedora_commons:

      repo: 'https://github.com/LafayetteCollegeLibraries/puppet-fedora_commons.git'

  symlinks:
    sufia_tomcat: "#{source_dir}"
